### PR TITLE
Add ISO8601Duration

### PR DESCRIPTION
**Pull request by vespertilian**
Looking forward to your feedback.

Please note: I grabbed examples from the popular date format libraries, moment, luxon, date-fns. The Moment library seems to be based off a python library that allows + prefixes. Not sure if this is really 100% ISO8601 compliant. I think matching to the formats the popular date format libraries expect, makes the most sense. Let me know what you think. 

Thanks!

### CODE REVIEW

**Comment by vespertilian** [comment]
Also can you lint to issue #503 thanks

**Comment by ardatan** [comment]
Awesome! We don't prefer to add lock files so could you remove that and also I think the exported value isn't a GraphQLScalarType instance like here;
https://github.com/Urigo/graphql-scalars/blob/master/src/scalars/Currency.ts#L17

Could you export `GraphQLScalarType` instance like above with `PURE` magic comment to force bundlers to do treeshaking for this type if it is not used? 
Thanks!

**Comment by ardatan** [comment]
Thank you @vespertilian !!! <3

**Comment by vespertilian** [comment]
@ardatan 

Thanks, sorry I was so tardy on getting to the updates!

:tada:

**Pull request merged**
