### PR TITLE
(MongoDB) ObjectID Scalar Type/Commit message convention

### PR DESCRIPTION
**Pull request by toondaey**
This PR does 2 things:

- It adds the mongodb object id scalar type to the existing definitions.

- Commit messages enforcement for future contributions and contributors. Please see [Conventional Commits][commit-convention] for commit messages conventions and [Commitlint][commitlint-package] npm package for implementation examples and explanations

Further, the usage of the commit linting has been added to the [Contributions](https://github.com/toondaey/graphql-scalars/blob/original/CONTRIBUTING.md) guidelines file.

[commit-convention]: https://www.conventionalcommits.org/en/v1.0.0/
[commitlint-package]: https://commitlint.js.org/#/

### CODE REVIEW

**Comment by ardatan** [comment]
@toondaey Could you rebase the conflicts?

**Comment by toondaey** [comment]
@ardatan All done now.

**Comment by ardatan** [comment]
I think `package.json` still conflicts :)

**Comment by toondaey** [comment]
@ardatan  All done now.

**Comment by ardatan** [comment]
Thank you @toondaey !

**Pull request merged**
