### PR TITLE
New locale scalar

### PR DESCRIPTION
**Pull request by syl-oh**
## Description

To implement new Locale scalar, it uses [language-tags](https://www.npmjs.com/package/language-tags).

Related issue: #1177 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Add unit test file for valid locale and invalid locales to test all methods of the scalar.

**Test Environment**:
- OS: Mac OS X 10.15.7
- GraphQL Scalars Version: Same as project
- NodeJS: v14.17.3

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests and linter rules pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ardatan** [comment]
Thank you for the PR! Is it possible to avoid adding any dependency for this scalar?

**Comment by syl-oh** [comment]
There are no regex I can use, I didn't want to copy over the data (plus the logic to parse and identify) for those tags in here because it won't be kept up to date.

**Comment by syl-oh** [comment]
Hello @ardatan what should happen now ?

**Comment by ardatan** [comment]
I actually don't want to add a dependency just for this scalar. All of the users will install this even if they are not using `Locale`. We avoided to have external dependencies so far. I think we should keep this in that way.

**Comment by syl-oh** [comment]
Alright 👍

**Comment by Xmaxer** [comment]
@badrange I am looking to add a dependency free alternative here: #1179

**Comment by badrange** [comment]
Wonderful! I think you meant to reference this PR: #1450

**Comment by Xmaxer** [comment]
Apologies! You're right.

**Pull request closed without merging**
