### PR TITLE
Email address validation is wrong. Allowing sree@sree as a valid email.

### PR DESCRIPTION
**Pull request by ksreejithnair**
Email Address validation is wrong, it's allowing sree@sree as a valid email address.

### CODE REVIEW

**Comment by ardatan** [comment]
We are following RFC822 specs for EmailAddress scalar. Are you sure this is supported by RFC822 spec?

**Comment by ksreejithnair** [comment]
RFC 822 was obsoleted in 2001 by RFC 2822, which in turn was obsoleted in 2008 by RFC 5322. The status of RFCs can be checked from the RFC Editor’s RFC database. My fix is not based on latest spec, but what we have in the package is terribly wrong. ard@ard is not a valid email.

**Comment by ardatan** [comment]
Hmm I see but this will be a breaking change then.

**Comment by ksreejithnair** [comment]
Honestly I believe nobody might be using it for validation so far or might not have written their test cases for email validation , I don't think any of the system will accept that. However, if you want we can add a EmailAdressWithCom or EmailAddressLatest scalar type? Ad provide a deprecation warning for some time?

**Comment by marklawlor** [comment]
The [HTML5 spec](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address) provides a regex should be used by browsers for the `<input type="email" />` field validation. Its a documented "willful violation of RFC 5322", but if its good enough for major browsers, its probably good enough for this library.

HTML5 spec email-regex
```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
```

**Comment by ardatan** [comment]
@marklawlor I think HTML5 spec would be enough.

**Comment by ksreejithnair** [comment]
Sorry that I couldn't get back to you in time. There is already bug raised with Safari and it is getting fixed. Please reopen this PR. https://bugs.webkit.org/show_bug.cgi?id=27457

**Comment by marklawlor** [comment]
> Sorry that I couldn't get back to you in time. There is already bug raised with Safari and it is getting fixed. Please reopen this PR. https://bugs.webkit.org/show_bug.cgi?id=27457

@ksreejithnair Did you link the correct issue? That bug report from 11 years ago while webkit was first implementing the HTML5 spec and is marked as resolved.

**Pull request closed without merging**
